### ISSUE TITLE
Indic Language ID Dataset

### ISSUE THREAD

**Issue by col1aborate** [Open-Speech-EkStep/vakyansh-models#16]
Hello Vakyansh team,

My team and me are working on the Indic Language ID dataset for various tasks like Abuse word detection, ASR for downstream tasks, Indic Language Identification from audio, etc. We have thoughts of contributing towards the Indic corpus, to help it to grow further.

Also, We are eager to know whether Open-Speech-EkStep is open to share or collaborate on the Vakyansh Indic Language ID dataset to enhance the models for social welfare and community support. We are open to collaborate over different various Indic Language ID corpus, which consists of 16 Indic languages, named Assamese, Bengali, Bhojpuri, English, Gujarati, Hindi, Haryanvi, Kannada, Malayalam, Marathi, Odia, Punjabi, Rajasthani, Tamil, Telugu, Urdu. Each of the languages are having minimum >83 hours of audio data.

Anticipating Favourable Response.

Thanks and Regards.

**Comment by harveenchadha** [comment]
Please contact me on my [email](harveen.chadha@thoughtworks.com) if you want to collaborate further.
