### ISSUE TITLE
vakyansh-wav2vec2-indian-english-enm-700 - result improvement

### ISSUE THREAD

**Issue by programmeddeath1** [Open-Speech-EkStep/vakyansh-models#17]
Hi I have used your Indian english model 'vakyansh-wav2vec2-indian-english-enm-700' to run speech to text on a few Indian youtube audios.

The results are quite good, but there are a few errors for certain free-spoken sentences. Here is the audio sample - 'https://github.com/programmeddeath1/webhost/blob/master/9_4.wav'
 The text output is as follows
'''
universe a you know i think for us while this is twenty wat now one years ago ri and india was going through a golden phace you know where youd already had sushmitayanashwaria whohad wanyu had dyana haden and yumla mukhi that had become isworld so there were tre
'''

I also tried with the kenlm language models for Indian English using the pyctc decoder, the results were slightly worse.

Can you guide me to how I can increase the accuracy for such audios, do I need to finetune the wave2vec on more Indian data, or can this be fixed with a better decoder like mbart. I could not find resources to replace the current encoder and use the bart encoder instead, so it would be great if you could guide me with this.

Thanks in advance!

**Comment by harveenchadha** [comment]
For increasing the accuracy in such videos you can collect some data and try to finetune again from the last provided checkpoint. Also if you are working on some particular domain, its good to create a new language model in that domain for the common words you are expecting.
