### ISSUE TITLE
Query: How to indentify multiple languages in a single speech file with time stamp.

### ISSUE THREAD

**Issue by aj7tesh** [Open-Speech-EkStep/vakyansh-models#19]
Hi Vakyansh team,
so this is more of a query and not an issue
is there a way/means to split an audio file into chunks based on the language of chunk. Lets say an audio has two languages in it english or hindi (the person speaks in hinglish) or english and some foreign language, is there a way to segregate chunks in such a case

**Comment by harveenchadha** [comment]
This is actually a very difficult problem to solve at this moment.
What we have tried:

1. Training a hinglish model but the finetuning dataset has to be huge for this.
2. Split chunks of audio on the basis of VAD(Voice Activity Detection) and then classifying every chunk into which language is spoken and then running the ASR of that language.

Both approaches have failed for us. If you find a good way to solve this, please do let us know.

**Comment by harveenchadha** [comment]
Closing this for now. Please feel free to open again.
