### ISSUE TITLE
Training / inference script for the models

### ISSUE THREAD

**Issue by naveenv2** [Open-Speech-EkStep/vakyansh-models#2]
Hi,

Thanks for the great collection of models.

I would like to fine-tune the existing models on my own dataset. Could you please share the instructions for the same, or point me to a training & inference script?

Thanks.

**Comment by harveenchadha** [comment]
Hi @naveenv2,

The training and inference script are present here:

https://github.com/Open-Speech-EkStep/vakyansh-wav2vec2-experimentation
