### ISSUE TITLE
Pretrained model 

### ISSUE THREAD

**Issue by GarimaNarang** [Open-Speech-EkStep/vakyansh-models#27]
Hi,
Is there a way to use the below pre-trained model for transcribing audio?? 
https://storage.googleapis.com/vakyansh-open-models/pretrained_models/vakyansh-conformer-ssl/ssl_conformer_large_e178.nemo

**Comment by tanmayh-fg** [comment]
Even I have the same question, I couldn't get any of the other models to work, they are giving blank output. Is this repository no longer being maintained? Any help would be appreciated

**Comment by harveenchadha** [comment]
Hey! This project is no longer maintained but I would like to answer your question.

The pretrained models are the models which give you embeddings, they are not mapped to any characters. You can say it is a foundational model of speech, it on its own is not meant to give any readable output. You need to finetune it on a downstream task like ASR to get an output.

**Comment by tanmayh-fg** [comment]
Got it, thank you for clarifying
