### ISSUE TITLE
Unable to use fine-tuned english speech-to-text model with hugging face transformers library

### ISSUE THREAD

**Issue by tirthshah17** [Open-Speech-EkStep/vakyansh-models#6]
First of all thank you for open sourcing speech recognition models. This is indeed a great project. I did checkout the speech-to-text model for hindi language that is uploaded on hugging face. @harveenchadha shared a post with interactive notebook on LinkedIn. I did explored that and accuracy for me was up to the mark. I was wandering if there was a way of doing exact same thing for english language as well? For this I performed the following steps : 

1) Took [https://huggingface.co/Harveenchadha/vakyansh-wav2vec2-hindi-him-4200/tree/main]() as starting point.
2) Replaced pytorch_model.bin model file with [https://storage.googleapis.com/vakyansh-open-models/models/english/en-IN/enm_700.pt](url) and converted .pt model file to pytorch_model.bin file.
3) Modified vocab.json file with the mappings given in [https://storage.googleapis.com/vakyansh-open-models/models/english/en-IN/dict.ltr.txt](url).
4) Used this a model checkpoint and then followed the same steps as in notebook - [https://colab.research.google.com/github/harveenchadha/bol/blob/main/demos/hf/hindi/hf_hindi_him_4200_demo.ipynb#scrollTo=pZ5rnYAt_rB1](url) 

But I get the error at this point - 

CODE -

```py
from transformers import Wav2Vec2ForCTC, Wav2Vec2Processor
MODEL_PATH = '../input/custom-wav2vec-english-enm-700'
model = Wav2Vec2ForCTC.from_pretrained(MODEL_PATH)
```

ERROR - 

```py
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
/opt/conda/lib/python3.7/site-packages/transformers/modeling_utils.py in from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
   1204                 try:
-> 1205                     state_dict = torch.load(resolved_archive_file, map_location="cpu")
   1206                 except Exception:

/opt/conda/lib/python3.7/site-packages/torch/serialization.py in load(f, map_location, pickle_module, **pickle_load_args)
    593                     return torch.jit.load(opened_file)
--> 594                 return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
    595         return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)

/opt/conda/lib/python3.7/site-packages/torch/serialization.py in _load(zip_file, map_location, pickle_module, pickle_file, **pickle_load_args)
    852     unpickler.persistent_load = persistent_load
--> 853     result = unpickler.load()
    854 

ModuleNotFoundError: No module named 'fairseq'

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
<ipython-input-3-16328c444ea2> in <module>
      6     return processor, model
      7 
----> 8 processor, model = load_model()

<ipython-input-3-16328c444ea2> in load_model()
      3     MODEL_PATH = '../input/custom-wav2vec-english-enm-700'
      4     processor = Wav2Vec2Processor.from_pretrained(MODEL_PATH)
----> 5     model = Wav2Vec2ForCTC.from_pretrained(MODEL_PATH)
      6     return processor, model
      7 

/opt/conda/lib/python3.7/site-packages/transformers/modeling_utils.py in from_pretrained(cls, pretrained_model_name_or_path, *model_args, **kwargs)
   1206                 except Exception:
   1207                     raise OSError(
-> 1208                         f"Unable to load weights from pytorch checkpoint file for '{pretrained_model_name_or_path}' "
   1209                         f"at '{resolved_archive_file}'"
   1210                         "If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True. "

OSError: Unable to load weights from pytorch checkpoint file for '../input/custom-wav2vec-english-enm-700' at '../input/custom-wav2vec-english-enm-700/pytorch_model.bin'If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True. 
```
Any assistance you can provide would be greatly appreciated.

Thank you

**Comment by harveenchadha** [comment]
Hi you need the complete fairseq setup to run the code. We are already in the process of converting models.

You can find the english model on huggingface [here](https://huggingface.co/Harveenchadha/vakyansh-wav2vec2-indian-english-enm-700/tree/main)

**Comment by harveenchadha** [comment]
[Demo](https://github.com/harveenchadha/bol/blob/main/demos/hf/english/hf_english_enm_700_demo.ipynb) in colab.
