### ISSUE TITLE
How to use the pre-trained models?

### ISSUE THREAD

**Issue by ekdnam** [Open-Speech-EkStep/vakyansh-models#8]
Are there any scripts available that can guide one on how to utilize the pre-trained models?

**Comment by Priyanshi-Shah** [comment]
Hi,

Please refer to the README.md in our [vakyansh-wav2vec2-experimentation.git](https://github.com/Open-Speech-EkStep/vakyansh-wav2vec2-experimentation.git) repository.

You will find all the necessary documentation there.

**Comment by harveenchadha** [comment]
Closing this for now. Please feel free to open if you still have some difficulty running the pretrained models.
